### ISSUE TITLE
IPAddressField has been deprecated

### ISSUE THREAD

**Issue by oscarelotero** [jamesturk/django-honeypot#15]
admin_honeypot.LoginAttempt.ip_address: (fields.W900) **IPAddressField** has been deprecated. Will be removed in Django 1.9.
Use **GenericIPAddressField** instead.

**Comment by oscarelotero** [comment]
Wrong package!

**Comment by jamesturk** [comment]
this most likely is an issue in https://github.com/dmpayton/django-admin-honeypot

a different project
