### ISSUE TITLE
Override template without editing source package?

### ISSUE THREAD

**Issue by craigmaloney** [jamesturk/django-honeypot#28]
I'm not understanding how to override the template without writing to the honeypot templates in the package. Is there a way to do this, and if so could this be explained more clearly in the documentation?

Thanks!

**Comment by jamesturk** [comment]
If you put a template with the same path in your templates directory yours
will be used instead of the package's.

https://docs.djangoproject.com/en/3.0/howto/overriding-templates/ is
actually probably the best resource for this, as it isn't specific to this
project.

**Comment by craigmaloney** [comment]
Hm, I tried this, but didn't seem to have much luck. Does it need to have the honeypot directory as well?

**Comment by jamesturk** [comment]
Yes, include the honeypot part of the path :)

**Comment by craigmaloney** [comment]
Ah, found my issue was related to the site-packages getting polled before the local template directories. It's working now.

Thanks for the quick response!
