### ISSUE TITLE
Cannot Save Changes On Admin With Middleware

### ISSUE THREAD

**Issue by 9mido** [jamesturk/django-honeypot#30]
Using the combined middleware of this app, HoneypotMiddleware, I cannot save anything I try to change on admin without getting the 400 bad request error page honeypot/honeypot_error.html. 

Nothing is entered into the value that the honeypot input field uses when I try to save. 

Removing the middleware and honeypot configuration from settings.py completely fixed the problem. It would still be useful to have django-honeypot work even on admin pages.

**Comment by jamesturk** [comment]
Can you give a bit more context?  Most helpful would be a small isolated
case, but any code you can share to reproduce would be appreciated.

**Comment by 9mido** [comment]
```
INSTALLED_APPS = ['honeypot',]

MIDDLEWARE = ['honeypot.middleware.HoneypotMiddleware',]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
    }
]

HONEYPOT_FIELD_NAME = "name"
HONEYPOT_VALUE = ""
```

Added the following CSS to admin to make the honeypot input invisible:

https://stackoverflow.com/a/37317429


admin-extra.css:

```
.form-input{
        opacity: 0;
        position: absolute;
        top: 0;
        left: 0;
        height: 0;
        width: 0;
        z-index: -1;
}
```

honeypot_error.html:

```
<title>400 Bad Request</title>
<meta name="description" content="Error Request aborted">

<h1>400 Bad Request</h1>
<p>Error Request aborted.</p>
```


honeypot_field.html:

```


<div class="form-input">

        <input type="text" name="{{fieldname}}" value="{{value}}" />
</div>
```

The HTML templates overridden and are located in:

project_name/templates/honeypot/

**Comment by 9mido** [comment]
@jamesturk According to another django expert I asked on reddit, it seems that this is happening because "If you have another field on the submission that has name="name" then this will cause the failure."

Changing the HONEYPOT_FIELD_NAME = "field-name" for example causes the save functionality to work again.

**Comment by jamesturk** [comment]
Thanks, I'll add a warning to the docs about this.
