### ISSUE TITLE
Conflict issue in django4

### ISSUE THREAD

**Issue by markflorence728** [jamesturk/django-honeypot#59]
`
The conflict is caused by:
    The user requested Django==4.0.1
    django-honeypot 1.0.2 depends on Django<4.0 and >=2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
`

I am getting a conflict error with this package in django4.0.1.
Looks like you didn't dump it to django4 yet. Hope to see the update as soon as possible.

**Comment by jamesturk** [comment]
Thanks for pointing this out, just pushed up 1.0.3 which supports 4.0 (no code changes).
