### ISSUE TITLE
Upgrading to Django v5.0 downgrades django-honeypot from v1.0.4 to v0.9.0

### ISSUE THREAD

**Issue by cclauss** [jamesturk/django-honeypot#85]
Why did `pipenv` make this downgrade in `Pipfile.lock`?
```diff
        "django": {
-            "markers": "python_version >= '3.8'",
-            "version": "==4.1.13"
+            "markers": "python_version >= '3.10'",
+            "version": "==5.0"
        },
        "django-honeypot": {
-            "version": "==1.0.4"
+            "version": "==0.9.0"
        },
```
Fixed in:
* #86 but not yet released to PyPI.
---
% `python3.12 -m venv .venv`
% `source .venv/bin/activate`
% `pip install --upgrade pip`
% `pip install django==5.0 django-honeypot==1.0.4` --> **_Failure_**
% `pip install django==5.0 django-honeypot` --> Success but with `django-honeypot` downgraded to v0.9.0

# Please release a new version to PyPI.

**Comment by cclauss** [comment]
% `python3.12 -m venv .venv`
% `source .venv/bin/activate`
% `pip install --upgrade pip`
% `pip install django==5.0 django-honeypot==1.0.4` --> **_Failure_**
% `pip install django==5.0 django-honeypot` --> Success but with `django-honeypot` downgraded to v0.9.0

Please release a new version to PyPI.

**Comment by jamesturk** [comment]
thanks for your help testing this and cleaning things up, just pushed a release of 1.1.0

**Comment by cclauss** [comment]
Python 3.12 support is missing at the bottom left of
* https://pypi.org/project/django-honeypot

<img width="271" alt="image" src="https://github.com/jamesturk/django-honeypot/assets/3709715/5275ec61-495a-4021-bbb3-a39d48868b7c">
