### ISSUE TITLE
check_honeypot Decorator and classed based views

### ISSUE THREAD

**Issue by hkage** [jamesturk/django-honeypot#9]
Hi there,

the `check_honeypot` currently only works with view methods as the inner decorator function assumes to be `request` the first argument. I tried to use the application with class based views, but the decorator will get passed `self` as the first argument.

Just an idea for an improvement!

With kind regards,
Henning

**Comment by Zalkota** [comment]
Could you please elaborate on this? How to I add the decorator to a class?
